"""Export a PostgreSQL database to a self-contained SQL dump file.

This is a lightweight fallback when `pg_dump` is not available on Windows.
It produces standard SQL (DROP, CREATE, INSERT, sequence reset) that can be
restored into another PostgreSQL-compatible database such as Supabase or Neon.

Usage:
    export DATABASE_URL="postgresql://user:pass@host:port/dbname"
    python scripts/export_postgres_to_sql.py [output.sql]
"""
import os
import sys
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from sqlalchemy import create_engine, MetaData, inspect, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable, DropTable

# Order respects foreign-key dependencies. Reverse it for DROP statements.
TABLE_ORDER = [
    'departments',
    'schools',
    'employees',
    'users',
    'attendance',
    'leaves',
    'leave_balances',
    'leave_balance_init',
    'advances',
    'payrolls',
    'holidays',
    'school_schedules',
    'audit_logs',
    'password_resets',
    'attendance_locks',
    'employee_schools',
    'app_config',
]


def get_tables_in_order(engine):
    """Return reflected Table objects in dependency order, skipping missing ones."""
    metadata = MetaData()
    metadata.reflect(bind=engine)
    ordered = []
    for name in TABLE_ORDER:
        if name in metadata.tables:
            ordered.append(metadata.tables[name])
    # Append any extra tables not in the hardcoded list
    for name, table in metadata.tables.items():
        if table not in ordered:
            ordered.append(table)
    return ordered


def reset_sequence_sql(table):
    """Return SQL to reset the serial sequence for a table, or None."""
    pk_cols = [c for c in table.primary_key.columns]
    if len(pk_cols) != 1:
        return None
    pk = pk_cols[0]
    if not pk.autoincrement:
        return None
    seq_name = f"{table.name}_{pk.name}_seq"
    return (
        f"SELECT setval('{seq_name}', COALESCE((SELECT MAX({pk.name}) FROM {table.name}), 1), true);\n"
    )


def main():
    database_url = os.environ.get('DATABASE_URL') or os.environ.get('SQLALCHEMY_DATABASE_URI')
    if not database_url:
        print('Error: set DATABASE_URL or SQLALCHEMY_DATABASE_URI.')
        sys.exit(1)

    # Normalize to psycopg dialect if plain postgresql://
    if database_url.startswith('postgres://'):
        database_url = database_url.replace('postgres://', 'postgresql+psycopg://', 1)
    elif database_url.startswith('postgresql://'):
        database_url = database_url.replace('postgresql://', 'postgresql+psycopg://', 1)

    output_file = sys.argv[1] if len(sys.argv) > 1 else 'postgres_backup.sql'

    engine = create_engine(database_url)
    tables = get_tables_in_order(engine)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('-- Robo Pirate Payroll PostgreSQL backup\n')
        f.write('-- Generated by export_postgres_to_sql.py\n\n')
        f.write('SET session_replication_role = replica;\n\n')

        # DROP in reverse order
        for table in reversed(tables):
            f.write(f'DROP TABLE IF EXISTS "{table.name}" CASCADE;\n')
        f.write('\n')

        # CREATE and INSERT in dependency order
        for table in tables:
            # CREATE TABLE
            create_sql = str(CreateTable(table).compile(dialect=postgresql.dialect()))
            f.write(create_sql)
            if not create_sql.endswith('\n'):
                f.write('\n')

            # INSERT data
            columns = list(table.columns.keys())
            if not columns:
                continue
            quoted_cols = ', '.join(f'"{c}"' for c in columns)

            with engine.connect() as conn:
                rows = conn.execute(table.select()).fetchall()

            if not rows:
                continue

            for row in rows:
                values = dict(row._mapping)
                stmt = table.insert().values(values).compile(
                    dialect=postgresql.dialect(),
                    compile_kwargs={'literal_binds': True}
                )
                f.write(str(stmt) + ';\n')
            f.write('\n')

            seq_sql = reset_sequence_sql(table)
            if seq_sql:
                f.write(seq_sql + '\n')

        f.write('SET session_replication_role = DEFAULT;\n')

    print(f'Backup written to {output_file}')
    print(f'Tables exported: {", ".join(t.name for t in tables)}')


if __name__ == '__main__':
    main()
